workflows:
  flutter-workflow:
    name: Flutter Workflow
    # Use a valid machine type from the error message list
    instance_type: mac_mini_m2 
    
    scripts:
      - name: Get Flutter packages
        script: | 
          flutter pub get

      - name: Build iOS App
        script: | 
          flutter build ios --no-codesign
          
    artifacts:
      - build/ios/iphoneos/Runner.app