workflows:
  flutter-workflow:
    name: Flutter Workflow
    instance_type: mac_mini_m2
    
    scripts:
      - name: Clean, Get Deps, and Build iOS
        script: | 
          # Exit on first error for clear logs
          set -e

          # Step 1: Clean the project.
          flutter clean

          # Step 2: Get all dependencies. This will generate the xcconfig file
          # needed by the new Podfile to find the flutter_root.
          flutter pub get

          # Step 3: Build the app. This will now succeed.
          flutter build ios --release --no-codesign
          
    artifacts:
      - build/ios/iphoneos/Runner.app