workflows:
  flutter-workflow:
    name: Flutter Workflow
    instance_type: macos_m2
    
    scripts:
      - name: Get Flutter packages
        script: | 
          flutter pub get

      - name: Build iOS App
        script: | 
          flutter build ios --no-codesign
          
    artifacts:
      - build/ios/iphoneos/Runner.app