workflows:
  flutter-workflow:
    name: Flutter Workflow
    instance_type: mac_mini_m2

    environment:
      flutter: stable  # or specific version like 3.19.6
      xcode: latest
      cocoapods: default
      vars:
        CM_CLEAN: true

    scripts:
      - name: Clean, Get Deps, and Install Pods
        script: |
          set -e
          flutter clean
          flutter pub get

          cd ios
          pod install
          cd ..

      - name: Build iOS Release (No Code Signing)
        script: |
          flutter build ios --release --no-codesign --obfuscate --split-debug-info=build/debug_info

    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/*.ipa
      - build/debug_info/**  # include if you added split-debug-info

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
