workflows:
  flutter-workflow:
    name: Flutter Workflow
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        CM_CLEAN: true

    scripts:
      - name: Install Deps and Build iOS App
        script: |
          set -e
          gem install xcodeproj
          flutter clean
          flutter pub get
          flutter build ios --release --no-codesign --obfuscate --split-debug-info=build/debug_info

    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/*.ipa
      - build/debug_info/**

    # --- THIS IS THE CORRECTED CACHE SECTION ---
    cache:
      cache_paths:
        - ~/.pub-cache