workflows:
  flutter-workflow:
    name: Flutter Workflow
    instance_type: mac_mini_m2
    
    scripts:
      - name: Build Flutter iOS App
        script: | 
          # Exit on first error
          set -e

          # Step 1: Install Flutter dependencies, which creates podhelper
          flutter pub get

          # Step 2: Go into the iOS folder and install pods
          cd ios
          pod install

          # Step 3: Go back to the root and build the app
          cd ..
          flutter build ios --release --no-codesign
          
    artifacts:
      - build/ios/iphoneos/Runner.app