workflows:
  flutter-workflow:
    name: Flutter Workflow
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        CM_CLEAN: true

    scripts:
      - name: Clean, Get Deps, and Install Pods
        script: |
          set -e
          flutter clean
          flutter pub get

          # Optional: Manually run pod install just to be sure
          cd ios
          pod install
          cd ..

      - name: Build iOS Release (No Code Signing)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/*.ipa  # optional, if you export ipa in future

    # Optional: Enable this if you later want code signing
    # code_signing:
    #   provisioning_profiles:
    #     ios_profile: Your_Provisioning_Profile_Name
