workflows:
  flutter-workflow:
    name: Flutter Workflow
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        CM_CLEAN: true

    scripts:
  - name: Rebuild iOS folder and Build App
    script: |
      set -e

      echo "--- 1. Installing dependencies ---"
      # We don't need xcodeproj anymore, but it's harmless to keep.
      gem install xcodeproj
      flutter pub get

      echo "--- 2. Recreating the iOS folder from scratch ---"
      rm -rf ios
      flutter create --platforms=ios .

      echo "--- 3. Restoring critical configuration files ---"
      cp ios_config_backup/Info.plist ios/Runner/
      cp -r ios_config_backup/Assets.xcassets ios/Runner/
      cp ios_config_backup/Podfile ios/ # <-- THE NEW, CRITICAL LINE
      # Uncomment the next line if you use Firebase
      # cp ios_config_backup/GoogleService-Info.plist ios/Runner/

      echo "--- 4. Building the iOS App ---"
      flutter build ios --release --no-codesign --obfuscate --split-debug-info=build/debug_info