workflows:
  flutter-workflow:
    name: Flutter Diagnostic Workflow
    instance_type: mac_mini_m2
    
    scripts:
      - name: Diagnostic Script
        script: | 
          # Exit on first error for clear logs
          set -e

          echo "----------- SCRIPT START -----------"
          
          echo " "
          echo "----------- STEP 1: Running flutter doctor -v -----------"
          flutter doctor -v

          echo " "
          echo "----------- STEP 2: Running flutter clean -----------"
          flutter clean
          
          echo " "
          echo "----------- STEP 3: Running flutter pub get -----------"
          flutter pub get

          echo " "
          echo "----------- STEP 4: Listing contents of the 'ios' directory -----------"
          # This will show us if the 'Flutter' sub-directory was created
          ls -la ios/
          
          echo " "
          echo "----------- STEP 5: Attempting the build -----------"
          flutter build ios --release --no-codesign
          
          echo " "
          echo "----------- SCRIPT END: BUILD SUCCEEDED! -----------"
          
    artifacts:
      - build/ios/iphoneos/Runner.app