workflows:
  flutter-workflow:
    name: Flutter Workflow
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        CM_CLEAN: true

    scripts:
      - name: Rebuild iOS folder and Build App
        script: |
          set -e

          echo "--- 1. Recreating the iOS folder from scratch ---"
          rm -rf ios
          flutter create --platforms=ios .

          echo "--- 2. Restoring critical configuration files ---"
          # This copies your custom settings into the newly created folder.
          cp ios_config_backup/Info.plist ios/Runner/
          cp -r ios_config_backup/Assets.xcassets ios/Runner/
          cp ios_config_backup/Podfile ios/
          # Uncomment the next line if you use Firebase
          # cp ios_config_backup/GoogleService-Info.plist ios/Runner/

          echo "--- 3. Get packages & generate plugin registration file ---"
          # This MUST run AFTER the ios folder and Podfile are in place.
          # This command creates the .flutter-plugins-with-build-configuration file.
          flutter pub get

          echo "--- 4. Building the iOS App ---"
          # The flutter build command will now find all necessary files and succeed.
          flutter build ios --release --no-codesign --obfuscate --split-debug-info=build/debug_info

    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/*.ipa
      - build/debug_info/**

    cache:
      cache_paths:
        - ~/.pub-cache