workflows:
  flutter-workflow:
    name: Flutter Workflow
    instance_type: mac_mini_m2
    
    scripts:
      - name: Install and Build iOS App
        script: | 
          # Exit on first error
          set -e

          # Step 1: Prime the Flutter environment and get verbose debug info
          flutter doctor -v

          # Step 2: Install Flutter dependencies, which creates podhelper
          flutter pub get

          # Step 3: Let Flutter handle the entire build process, including pod install
          flutter build ios --release --no-codesign
          
    artifacts:
      - build/ios/iphoneos/Runner.app