workflows:
  flutter-workflow:
    name: Flutter Workflow
    instance_type: mac_mini_m2
    
    scripts:
      - name: Clean, Get Deps, and Build iOS
        script: | 
          # Exit on first error for clear logs
          set -e

          # Step 1: Clean the project to remove any stale or broken state.
          # This is the most critical step for a reliable CI build.
          flutter clean

          # Step 2: Get all dependencies. This will now be forced to
          # regenerate the native integration files (like podhelper) from scratch.
          flutter pub get

          # Step 3: Build the app. It will now find a perfectly prepared project.
          flutter build ios --release --no-codesign
          
    artifacts:
      - build/ios/iphoneos/Runner.app