workflows:
  flutter-workflow:
    name: Flutter Workflow
    instance_type: mac_mini_m2
    
    scripts:
      - name: Install Flutter dependencies
        script: | 
          flutter pub get

      - name: Install iOS dependencies (CocoaPods)
        script: | 
          cd ios
          pod install

      - name: Build iOS App
        script: | 
          flutter build ios --release --no-codesign
          
    artifacts:
      - build/ios/iphoneos/Runner.app