name: mm_associates
description: "booking application"
publish_to: 'none'

version: 1.0.0+1

environment:
  # Use a recent stable Dart SDK constraint
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase (Updated to recent stable versions)
  firebase_core: ^3.1.1 # Or latest stable
  firebase_auth: ^5.1.1 # Or latest stable
  cloud_firestore: ^5.0.2 # Or latest stable
  firebase_storage: ^12.1.1 # Or latest stable

  # Auth & Sign In (Keep reasonably updated)
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0 # Stays the same
  intl_phone_field: ^3.2.0 # Recent version

  # Location & Maps (Update moderately)
  google_maps_flutter: ^2.2.5
  geolocator: ^12.0.0 # Major version jump might have API changes
  permission_handler: ^11.3.1
  haversine_distance: ^1.2.1 # Stays the same
  geocoding: ^3.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  photo_view: ^0.15.0

  # UI & Utilities (Update moderately)
  cupertino_icons: ^1.0.8
  # *** CORRECTED: Downgrade to resolve conflict ***
  font_awesome_flutter: ^9.2.0
  provider: ^6.1.2
  flutter_rating_bar: ^4.0.1 # Stays the same
  intl: ^0.19.0 # Updated for Dart 3+ compatibility
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  http: ^1.2.1 # Updated http
  flutter_dotenv: ^5.1.0 # Stays the same

  # Other dependencies (Update moderately)
  table_calendar: ^3.1.2
  share_plus: ^9.0.0 # Update share_plus
  shimmer: ^3.0.0 # Or the latest version
  firebase_crashlytics: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0 # Update lints

  # Mockito needed for tests
  mockito: ^5.4.4
  build_runner: ^2.4.11 # Keep compatible version

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/city.png
    - assets/.env
